/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package school.form;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import school.Student;

/**
 *
 * @author ASUS
 */
public class UpdateStudent extends javax.swing.JPanel {

    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        initComponents();
        init();
        try {
            readFile();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ListStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String oldImagePath;
    List<Student> list = null;
    int studentIndex = 0;

    private void init() {

        table.fixTable(jScrollPane1);

        //table.setAutoCreateRowSorter(true);
        table.setFillsViewportHeight(true);
        //desStudent.setWrapStyleWord(true);
    }

    private void readFile() throws ClassNotFoundException {
        //this part deserializes the list from file, and then iterates over its members

        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("students.bin"));
            list = (List) ois.readObject();
            int i = 1;
            for (Student st : list) {
                addDataTable(st, i);
                i += 1;
//                System.out.println(st.getId());
//                System.out.println(st.getName());
//                System.out.println(st.getScore());
//                System.out.println(st.getImage());
//                System.out.println(st.getAddress());
//                System.out.println(st.getDescription());
            }
        } catch (IOException ex) {
            Logger.getLogger(ListStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void addDataTable(Student st, int i) {
        table.addRow(new Object[]{st.getId(), st.getName(), st.getScore(), st.getAddress(), st.getDescription()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new swing.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new swing.Table();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idStudent = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameStudent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        scoreStudent = new javax.swing.JTextField();
        addressStudent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desStudent = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pathImage = new javax.swing.JTextField();
        jlabelImg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setOpaque(false);

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setRound(10);

        table.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MHS", "TenHS", "Diem", "Địa chỉ", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        table.setShowGrid(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT DANH SÁCH HỌC SINH");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã học sinh");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));

        idStudent.setEditable(false);
        idStudent.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(idStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 11, 248, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên HS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, -1, -1));

        nameStudent.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(nameStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 53, 248, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Điểm");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 99, -1, -1));

        scoreStudent.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(scoreStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 95, 248, -1));

        addressStudent.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPanel1.add(addressStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 131, 248, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Địa chỉ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 135, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Ghi chú");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 173, -1, -1));

        desStudent.setColumns(20);
        desStudent.setLineWrap(true);
        desStudent.setRows(5);
        desStudent.setWrapStyleWord(true);
        jScrollPane2.setViewportView(desStudent);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 173, 248, 55));

        jButton1.setText("Chọn file");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        pathImage.setEditable(false);
        pathImage.setText("pathImage");

        jlabelImg.setBackground(new java.awt.Color(255, 255, 255));
        jlabelImg.setForeground(new java.awt.Color(51, 102, 255));
        jlabelImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelImg.setText("image");
        jlabelImg.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathImage)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(pathImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 234, 330, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setText("Cập nhật");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 431, 113, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRowIndex = table.getSelectedRow();
        idStudent.setText(model.getValueAt(selectedRowIndex, 0).toString());
        nameStudent.setText(model.getValueAt(selectedRowIndex, 1).toString());
        addressStudent.setText(model.getValueAt(selectedRowIndex, 3).toString());
        desStudent.setText(model.getValueAt(selectedRowIndex, 4).toString());
        scoreStudent.setText(model.getValueAt(selectedRowIndex, 2).toString());

        studentIndex = findStudent(list, idStudent.getText());
        oldImagePath = list.get(studentIndex).getImage();
        ImageIcon ii = new ImageIcon(oldImagePath);

        // resize 
        Image image = ii.getImage().getScaledInstance(jlabelImg.getWidth(), jlabelImg.getHeight(), Image.SCALE_SMOOTH);

        pathImage.setText(oldImagePath);
        jlabelImg.setText("");
        jlabelImg.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_tableMouseClicked

    private int findStudent(List<Student> list, String id) {

        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getId().equals(id)) {
                return i;
            }
        }
        return -1;
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        String selectedImagePath;
        // filter file
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.setFileFilter(fnef);
        int showOpenDialog = browseImageFile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();

            ImageIcon ii = new ImageIcon(selectedImagePath);
            
            
            // resize 
            Image image = ii.getImage().getScaledInstance(jlabelImg.getWidth(), jlabelImg.getHeight(), Image.SCALE_SMOOTH);

            pathImage.setText(selectedImagePath);
            jlabelImg.setText("");
            jlabelImg.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        if (idStudent.getText().equals("") || nameStudent.getText().equals("") || scoreStudent.getText().equals("") || addressStudent.getText().equals("") || desStudent.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " Vui lòng điền đầy đủ thông tin !");
        } else {

            // add image into folder 
            InputStream inStream = null;
            OutputStream outStream = null;
            String imageSelect = pathImage.getText();
            try {
                String newImagePath = oldImagePath;
                if (!oldImagePath.equals(imageSelect)) {
                    // Lấy phần mở rộng của tệp được chọn
                    String extension = "";
                    int i = imageSelect.lastIndexOf('.');
                    if (i > 0) {
                        extension = imageSelect.substring(i + 1);
                    }

                    // delete file cũ
                    File oldFile = new File(oldImagePath);
                    System.out.println("oldImagePath: " + oldImagePath);
                    if (oldFile.delete()) {
                        System.out.println("Deleted the file: " + oldFile.getName());
                    }

                    // Thêm file mới
                    inStream = new FileInputStream(new File(imageSelect));
                    newImagePath = "ImageStudent/" + idStudent.getText() + "." + extension;
                    File file = new File(newImagePath);
                    outStream = new FileOutputStream(file);

                    int length;
                    byte[] buffer = new byte[1024];

                    // copy the file content in bytes
                    while ((length = inStream.read(buffer)) > 0) {
                        outStream.write(buffer, 0, length);
                    }

                }
                list.get(studentIndex).setName(nameStudent.getText());
                list.get(studentIndex).setAddress(addressStudent.getText());
                list.get(studentIndex).setDescription(desStudent.getText());
                list.get(studentIndex).setScore(Double.parseDouble(scoreStudent.getText()));
                list.get(studentIndex).setImage(newImagePath);

            } catch (IOException e) {
                e.printStackTrace();
            }

            // write file
            try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("students.bin"))) {
                oos.writeObject(list);
                JOptionPane.showMessageDialog(this, "Cập nhật thành công !");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Câp nhật học sinh KHÔNG thành công !!!!");
                e.printStackTrace();
            }
            // đọc lại bantrg
            try {
                table.setModel(new DefaultTableModel(null, new String[]{"MHS", "TenHS", "Điểm", "Địa chỉ", "Ghi chú"}));
                readFile();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressStudent;
    private javax.swing.JTextArea desStudent;
    private javax.swing.JTextField idStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabelImg;
    private javax.swing.JTextField nameStudent;
    private javax.swing.JTextField pathImage;
    private swing.RoundPanel roundPanel1;
    private javax.swing.JTextField scoreStudent;
    private swing.Table table;
    // End of variables declaration//GEN-END:variables
}
